### ISSUE TITLE
fractal转账会报错

### ISSUE THREAD

**Issue by junpengdong** [ByteJason/BTC-Script#1]
data: 'sendrawtransaction RPC error: {"code":-1,"message":"Non-string request body"}'
不知道你那边有没遇到这个问题

**Comment by ByteJason** [comment]
请问是哪个用了哪个链，哪个测试网还是主网

**Comment by ByteJason** [comment]
我这边没有报错，能麻烦将报错信息发全一些吗，我想看下是哪一行报错？
hex是否已经生成，在广播时候出错吗？
