### ISSUE TITLE
分形主网转账报错

### ISSUE THREAD

**Issue by W-VINCE** [ByteJason/BTC-Script#2]
![image](https://github.com/user-attachments/assets/b8ab61a3-a037-4b96-8491-15a1117c53ac)
有余额且是确认状态，但是获取不到可用的UTXO。换了好几个钱包都是这样。

**Comment by wujunze** [comment]
你用的哪个 RPC

**Comment by W-VINCE** [comment]
> 你用的哪个 RPC

![image](https://github.com/user-attachments/assets/3bf3283f-2e3b-4b37-a908-bcc308e0f744)
![image](https://github.com/user-attachments/assets/dfdc0f82-33da-479c-a143-b8e32e5e6298)

**Comment by wujunze** [comment]
> > 你用的哪个 RPC
> 
> ![image](https://private-user-images.githubusercontent.com/31689951/366477571-3bf3283f-2e3b-4b37-a908-bcc308e0f744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDM0NjksIm5iZiI6MTcyNjY0MzE2OSwicGF0aCI6Ii8zMTY4OTk1MS8zNjY0Nzc1NzEtM2JmMzI4M2YtMmUzYi00YjM3LWE5MDgtYmNjMzA4ZTBmNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDIyYmE1MzU0YWY1MGMwZWUzMzFkNTMxNGVmMmM1ZjQ4MjFlY2E3ZGFmYWRmMTMxM2U2ZGYzYmQxODliNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EZRA7w64QQ9ek-obewduV3exwXA7DhdGpHa_CvzcjwM) ![image](https://private-user-images.githubusercontent.com/31689951/366477685-dfdc0f82-33da-479c-a143-b8e32e5e6298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDM0NjksIm5iZiI6MTcyNjY0MzE2OSwicGF0aCI6Ii8zMTY4OTk1MS8zNjY0Nzc2ODUtZGZkYzBmODItMzNkYS00NzljLWExNDMtYjhlMzJlNWU2Mjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTllNmNiZmI4YTE2YjcyMDY1ZGM3YWIwZmU5ODgxMjQwMjJlMmZhN2YxMzI1MDkxZGZiMjEzYjI1OGQ2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I2vcVXJzHts7fsNIl4rH_LQRPEaUHEwmvDEFZXkG3RI)

查询 UTXO 的API 需要换一下

**Comment by ByteJason** [comment]
用最新的代码已经更新

**Comment by W-VINCE** [comment]
> 用最新的代码已经更新

非常感谢！
